# Generated by Django 5.2.17 on 2026-09-22 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(help_text='Name of the medical condition', max_length=200, verbose_name='condition name')),
                ('diagnosis_date', models.DateField(blank=True, help_text='Date when condition was diagnosed', null=True, verbose_name='diagnosis date')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the condition', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to=settings.AUTH_USER_MODEL, verbose_name='patient')),
                ('treating_doctor', models.ForeignKey(blank=True, limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treated_patients', to=settings.AUTH_USER_MODEL, verbose_name='treating doctor')),
            ],
            options={
                'verbose_name': 'medical history',
                'verbose_name_plural': 'medical histories',
                'db_table': 'medical_history',
                'ordering': ['-diagnosis_date', '-created_at'],
            },
        ),
    ]
