# Generated by Django 5.2.17 on 2026-09-22 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='symptom name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('category', models.CharField(blank=True, help_text='e.g., respiratory, gastrointestinal, neurological', max_length=100, verbose_name='category')),
                ('severity_levels', models.JSONField(blank=True, default=list, help_text='Available severity levels for this symptom', verbose_name='severity levels')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'symptom',
                'verbose_name_plural': 'symptoms',
                'db_table': 'symptoms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20, verbose_name='status')),
                ('chief_complaint', models.TextField(help_text='Primary reason for consultation', verbose_name='chief complaint')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_consultations', to=settings.AUTH_USER_MODEL, verbose_name='assigned doctor')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL, verbose_name='patient')),
            ],
            options={
                'verbose_name': 'consultation',
                'verbose_name_plural': 'consultations',
                'db_table': 'consultations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The follow-up question asked', verbose_name='question')),
                ('answer', models.TextField(blank=True, help_text="Patient's answer to the question", verbose_name='answer')),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_questions', to='consultations.consultation', verbose_name='consultation')),
            ],
            options={
                'verbose_name': 'follow-up question',
                'verbose_name_plural': 'follow-up questions',
                'db_table': 'follow_up_questions',
                'ordering': ['asked_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='moderate', max_length=20, verbose_name='severity')),
                ('duration', models.CharField(blank=True, help_text="e.g., '2 days', '1 week', '3 hours'", max_length=100, verbose_name='duration')),
                ('notes', models.TextField(blank=True, help_text='Additional details about the symptom', verbose_name='notes')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_symptoms', to='consultations.consultation', verbose_name='consultation')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_reports', to='consultations.symptom', verbose_name='symptom')),
            ],
            options={
                'verbose_name': 'patient symptom',
                'verbose_name_plural': 'patient symptoms',
                'db_table': 'patient_symptoms',
                'ordering': ['-reported_at'],
            },
        ),
    ]
