# Generated by Django 5.2.17 on 2026-09-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='ai_assessment_accepted',
            field=models.BooleanField(default=False, verbose_name='AI assessment accepted'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='diagnosis',
            field=models.TextField(blank=True, verbose_name='diagnosis'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor_notes',
            field=models.TextField(blank=True, verbose_name='doctor notes'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='follow_up_required',
            field=models.BooleanField(default=False, verbose_name='follow-up required'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='treatment_recommendation',
            field=models.TextField(blank=True, verbose_name='treatment recommendation'),
        ),
    ]
