# Generated by Django 5.2.17 on 2026-09-22 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalKnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='source name')),
                ('url', models.URLField(help_text='Source URL', max_length=500, verbose_name='URL')),
                ('source_type', models.CharField(choices=[('WHO', 'WHO'), ('MOH', 'Ministry of Health'), ('FDA', 'FDA'), ('HOSPITAL', 'Hospital'), ('LITERATURE', 'Literature'), ('GUIDELINE', 'Guideline')], max_length=20, verbose_name='source type')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deprecated', 'Deprecated')], default='pending', max_length=20, verbose_name='approval status')),
                ('last_verified_date', models.DateField(blank=True, help_text='Date when source was last verified', null=True, verbose_name='last verified date')),
                ('retrieval_config', models.JSONField(blank=True, default=dict, help_text='Configuration for retrieval from this source', verbose_name='retrieval config')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the source', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'medical knowledge source',
                'verbose_name_plural': 'medical knowledge sources',
                'db_table': 'medical_knowledge_sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RetrievedEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the retrieved document', max_length=500, verbose_name='title')),
                ('url', models.URLField(blank=True, help_text='URL of the source document', max_length=500, verbose_name='URL')),
                ('publication_date', models.DateField(blank=True, help_text='Date when the source was published', null=True, verbose_name='publication date')),
                ('retrieval_date', models.DateTimeField(auto_now_add=True, verbose_name='retrieval date')),
                ('relevance_score', models.FloatField(default=0.0, help_text='Score indicating relevance to the query', verbose_name='relevance score')),
                ('extracted_content', models.TextField(help_text='Content extracted from the source', verbose_name='extracted content')),
                ('key_points', models.JSONField(blank=True, default=list, help_text='Key points extracted from the content', verbose_name='key points')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieved_evidence', to='ai.aiassessment', verbose_name='AI assessment')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retrieved_evidence', to='knowledge.medicalknowledgesource', verbose_name='source')),
            ],
            options={
                'verbose_name': 'retrieved evidence',
                'verbose_name_plural': 'retrieved evidence',
                'db_table': 'retrieved_evidence',
                'ordering': ['-relevance_score', '-retrieval_date'],
            },
        ),
    ]
