# Generated by Django 5.2.17 on 2026-09-22 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='medication name')),
                ('generic_name', models.CharField(blank=True, max_length=200, verbose_name='generic name')),
                ('brand_names', models.JSONField(blank=True, default=list, help_text='List of brand names', verbose_name='brand names')),
                ('drug_class', models.CharField(choices=[('antibiotic', 'Antibiotic'), ('analgesic', 'Analgesic'), ('antihypertensive', 'Antihypertensive'), ('antidiabetic', 'Antidiabetic'), ('antidepressant', 'Antidepressant'), ('anticoagulant', 'Anticoagulant'), ('antiinflammatory', 'Anti-inflammatory'), ('other', 'Other')], default='other', max_length=20, verbose_name='drug class')),
                ('indications', models.JSONField(blank=True, default=list, help_text='Approved uses/indications', verbose_name='indications')),
                ('contraindications', models.JSONField(blank=True, default=list, help_text='Contraindications and warnings', verbose_name='contraindications')),
                ('known_interactions', models.JSONField(blank=True, default=list, help_text='Known drug-drug interactions', verbose_name='known interactions')),
                ('allergy_warnings', models.JSONField(blank=True, default=list, help_text='Allergy-related warnings', verbose_name='allergy warnings')),
                ('precautions', models.JSONField(blank=True, default=list, help_text='Important precautions', verbose_name='precautions')),
                ('reference_source', models.CharField(blank=True, help_text='Source of medication information', max_length=300, verbose_name='reference source')),
                ('last_verified_date', models.DateField(blank=True, help_text='Date when medication information was last verified', null=True, verbose_name='last verified date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'medication',
                'verbose_name_plural': 'medications',
                'db_table': 'medications',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribed_date', models.DateField(auto_now_add=True, verbose_name='prescribed date')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISCONTINUED', 'Discontinued'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, help_text='Additional prescription notes', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultations.consultation', verbose_name='consultation')),
                ('prescribing_doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_medications', to=settings.AUTH_USER_MODEL, verbose_name='prescribing doctor')),
            ],
            options={
                'verbose_name': 'prescription',
                'verbose_name_plural': 'prescriptions',
                'db_table': 'prescriptions',
                'ordering': ['-prescribed_date'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(help_text="e.g., '500mg', '10mg', '1 tablet'", max_length=100, verbose_name='dosage')),
                ('frequency', models.CharField(help_text="e.g., 'twice daily', 'every 8 hours', 'once daily'", max_length=100, verbose_name='frequency')),
                ('duration', models.CharField(help_text="e.g., '7 days', '2 weeks', '30 days'", max_length=100, verbose_name='duration')),
                ('instructions', models.TextField(blank=True, help_text='Specific instructions for taking this medication', verbose_name='instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='medications.medication', verbose_name='medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='medications.prescription', verbose_name='prescription')),
            ],
            options={
                'verbose_name': 'prescription medication',
                'verbose_name_plural': 'prescription medications',
                'db_table': 'prescription_medications',
                'ordering': ['prescription', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedicationInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('pharmacokinetic', 'Pharmacokinetic'), ('pharmacodynamic', 'Pharmacodynamic'), ('contraindicated', 'Contraindicated'), ('caution', 'Use with Caution')], max_length=20, verbose_name='interaction type')),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('contraindicated', 'Contraindicated')], max_length=20, verbose_name='severity')),
                ('description', models.TextField(help_text='Description of the interaction', verbose_name='description')),
                ('evidence_source', models.CharField(blank=True, help_text='Source of interaction information', max_length=300, verbose_name='evidence source')),
                ('recommendation', models.TextField(blank=True, help_text='Clinical recommendation for managing the interaction', verbose_name='recommendation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_med1', to='medications.medication', verbose_name='medication 1')),
                ('medication_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_med2', to='medications.medication', verbose_name='medication 2')),
            ],
            options={
                'verbose_name': 'medication interaction',
                'verbose_name_plural': 'medication interactions',
                'db_table': 'medication_interactions',
                'ordering': ['-severity', 'medication_1', 'medication_2'],
                'unique_together': {('medication_1', 'medication_2')},
            },
        ),
    ]
