# Generated by Django 5.2.17 on 2026-09-22 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_diagnosis', models.TextField(blank=True, help_text="Doctor's professional diagnosis", verbose_name='professional diagnosis')),
                ('clinical_notes', models.TextField(blank=True, help_text='Additional clinical notes', verbose_name='clinical notes')),
                ('treatment_recommendations', models.TextField(blank=True, help_text='Treatment recommendations by the doctor', verbose_name='treatment recommendations')),
                ('ai_suggestion_action', models.CharField(choices=[('ACCEPT', 'Accept'), ('MODIFY', 'Modify'), ('REJECT', 'Reject')], default='ACCEPT', max_length=20, verbose_name='AI suggestion action')),
                ('modifications_made', models.JSONField(blank=True, default=dict, help_text='Details of modifications made to AI suggestions', verbose_name='modifications made')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_review', to='consultations.consultation', verbose_name='consultation')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_reviews', to=settings.AUTH_USER_MODEL, verbose_name='doctor')),
            ],
            options={
                'verbose_name': 'doctor review',
                'verbose_name_plural': 'doctor reviews',
                'db_table': 'doctor_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
