# Generated by Django 5.2.17 on 2026-09-22 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms_identified', models.JSONField(blank=True, default=list, help_text='List of symptoms identified by AI', verbose_name='symptoms identified')),
                ('follow_up_questions', models.JSONField(blank=True, default=list, help_text='Generated follow-up questions', verbose_name='follow-up questions')),
                ('possible_conditions_list', models.JSONField(blank=True, default=list, help_text='List of possible conditions identified', verbose_name='possible conditions list')),
                ('warning_signs', models.JSONField(blank=True, default=list, help_text='Emergency or warning signs detected', verbose_name='warning signs')),
                ('urgency_level', models.CharField(choices=[('INFORMATIONAL', 'Informational'), ('ROUTINE_CONSULTATION', 'Routine Consultation'), ('PROMPT_MEDICAL_REVIEW', 'Prompt Medical Review'), ('URGENT_MEDICAL_ATTENTION', 'Urgent Medical Attention')], default='INFORMATIONAL', max_length=30, verbose_name='urgency level')),
                ('general_information', models.TextField(blank=True, help_text='General medical information for the patient', verbose_name='general information')),
                ('medication_information', models.JSONField(blank=True, default=list, help_text='Medication-related information', verbose_name='medication information')),
                ('recommended_next_step', models.TextField(blank=True, help_text='Recommended action for the patient', verbose_name='recommended next step')),
                ('sources', models.JSONField(blank=True, default=list, help_text='Sources used for the assessment', verbose_name='sources')),
                ('model_used', models.CharField(blank=True, help_text='AI model used for assessment', max_length=100, verbose_name='model used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assessment', to='consultations.consultation', verbose_name='consultation')),
            ],
            options={
                'verbose_name': 'AI assessment',
                'verbose_name_plural': 'AI assessments',
                'db_table': 'ai_assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PossibleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(help_text='Name of the possible condition', max_length=200, verbose_name='condition name')),
                ('likelihood', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20, verbose_name='likelihood')),
                ('confidence_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20, verbose_name='confidence level')),
                ('reasoning', models.TextField(blank=True, help_text='AI reasoning for this condition', verbose_name='reasoning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identified_conditions', to='ai.aiassessment', verbose_name='AI assessment')),
            ],
            options={
                'verbose_name': 'possible condition',
                'verbose_name_plural': 'possible conditions',
                'db_table': 'possible_conditions',
                'ordering': ['-confidence_level', 'condition_name'],
            },
        ),
    ]
