# Generated by Django 5.2.17 on 2026-09-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='condition name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icd_code', models.CharField(blank=True, help_text='International Classification of Diseases code', max_length=20, verbose_name='ICD code')),
                ('category', models.CharField(choices=[('infectious', 'Infectious Disease'), ('chronic', 'Chronic Condition'), ('acute', 'Acute Condition'), ('genetic', 'Genetic Disorder'), ('mental_health', 'Mental Health'), ('other', 'Other')], default='other', max_length=20, verbose_name='category')),
                ('common_symptoms', models.JSONField(blank=True, default=list, help_text='List of common symptoms associated with this condition', verbose_name='common symptoms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'medical condition',
                'verbose_name_plural': 'medical conditions',
                'db_table': 'medical_conditions',
                'ordering': ['name'],
            },
        ),
    ]
