# Generated by Django 5.2.17 on 2026-09-22 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('ai_assessment', 'AI Assessment'), ('medical_record_access', 'Medical Record Access'), ('prescription_access', 'Prescription Access'), ('other', 'Other')], max_length=30, verbose_name='action')),
                ('entity_type', models.CharField(blank=True, help_text='Type of entity affected (e.g., Consultation, Prescription)', max_length=100)),
                ('entity_id', models.CharField(blank=True, help_text='ID of the entity affected', max_length=100)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Details of changes made', verbose_name='changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/user agent string', verbose_name='user agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'), models.Index(fields=['action', 'timestamp'], name='audit_logs_action_474804_idx')],
            },
        ),
    ]
